### PR TITLE
fix the options Validate func

### PR DESCRIPTION
**Pull request by huangjiasingle**
replace one of the s.ClusterName to s.HostName of the Validate func.

### CODE REVIEW

**Comment by prydie** [comment]
Hi @huangjiasingle,

Good catch! Thanks for the PR - LGTM 👍 

Would you mind signing the Oracle Contributor Agreement (i.e. our CLA) and signing-off your commit so we can merge (see:  [CONTRIBUTING.md](https://github.com/oracle/mysql-operator/blob/master/CONTRIBUTING.md) for details)?

**Comment by huangjiasingle** [comment]
@prydie  ok， l also write the mariadb operator, maybe it's different from the mysq-operator. but most code of oeprator is repeat， although l write it by operator-skd.  the operator-sdk can't get the all event type  of the crd or k8s resource model, it's unfriendly. l want use oracle/mysql-operator S3 package to backup and restore.

**Comment by prydie** [comment]
Nice! Do let us know how you get on with your operator.

If you could drop a message here once you've submitted the CLA I'll chase up on our end.

**Comment by prydie** [comment]
Hey @huangjiasingle, did you manage to submit the CLA perchance?

**Comment by huangjiasingle** [comment]
@prydie  l will do it,  l have some questions to ask you. 
1. when the database data is too big or have many cluster to do backup in the some namespace,  does the operator work will ? do you have some performance testing?  
2. when the backup data is too big, upload to s3 storage. you use the os.Open(tmpFile) to get the file stream. may be it's will cost many time to open file. 
 3. when the operator is down .  when l recreate cluster or add the new cluster node. it's can work well ?

**Comment by prydie** [comment]
Great!

> when the database data is too big or have many cluster to do backup in the some namespace, does the operator work will ? do you have some performance testing?

Concurrent backup performance is bounded by the underlying hardware as backups are handled by one of the MySQL Cluster members' `mysql-agent` sidecar container rather than centrally by the operator. You should have no problem backing up many clusters (in the same namespace or otherwise). Do let us know if this isn't the case though as we haven't done extensive performance testing in this area.

Additionally, currently, the only backup tool we support is `mysqldump` which performs [logical backups](https://dev.mysql.com/doc/refman/8.0/en/glossary.html#glos_logical_backup) and as a result, has [performance and scalability considerations](https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html#mysqldump-performance) you should take into account when evaluating the MySQL Operator's suitability for your use case.

We've got support for [MySQL Enterprise Backup](https://dev.mysql.com/doc/refman/8.0/en/mysql-enterprise-backup.html) on the roadmap, however, which provides a much more scalable solution for users with an enterprise licence (#110).

> when the backup data is too big, upload to s3 storage. you use the `os.Open(tmpFile)` to get the file stream. may be it's will cost many time to open file.

You've hit on the arguably the biggest limitation of the current backup implementation. However, the main problem generally isn't around the performance reading/writing to the file (though it's certainly not ideal). Rather, the main issue is whether or not you have enough space to write all the data to disk temporarily. We've got uploading directly to S3 directly tracked by #148 and hopefully, we'll get it fixed for the next release (though of course contributions are always welcome 🙂 ).

> when the operator is down . when l recreate cluster or add the new cluster node. it's can work well ?

When the operator is down your existing MySQL Clusters will continue to operate (including self-healing). However, cluster lifecycle management operations such as creating new clusters or scaling existing clusters won't take effect until the operator is restarted. Additionally, you won't be able to start new backups (including scheduled backups), however, in-progress backups and restores will continue to execute.

**Comment by huangjiasingle** [comment]
@prydie  thanks.  I agree with your point of view. l think the already exist cluster basic performence shouldn't dependence operator.  
1. yell, upload data to s3 may be cause backup failed
2. may be should rm the backup data when the data was upload s3 success.

some time l think we should reduce the operator's ability, if the operator do many many things , it's maybe cause operator down. 

in my product env, it's have some mariadb cluster. maybe have some cron backup task or backup task. so l restruct the operator design. the operator create mariadb cluster. produce the backup task(include cron backup task) and sent it to mq. another container to do backup data and upload data to s3.  l can use the hpa to autoscale the backup container. when backup success or failed, call the operator api to upadate backup crd's status. I don't know if this is against the original intention of the operator ?

**Pull request closed without merging**
