### PR TITLE
fix backups to disk

### PR DESCRIPTION
**Pull request by Simon-Li**
this is for #147

### CODE REVIEW

**Comment by prydie** [comment]
Awesome, thanks @Simon-Li! Changes LGTM :+1: 

Would you mind rebasing your PR into a singe signed-off commit? Additionally, if you haven't already signed to [Oracle Contributor Agreement](https://www.oracle.com/technetwork/community/oca-486395.html) can you please do so.

@owainlewis Can we get the CI hooked up for third-party PRs and trigger a run for this prior to merging?

**Comment by Simon-Li** [comment]
Rebased and the OCA was submitted, thanks @prydie

**Comment by prydie** [comment]
@Simon-Li Did you submit the OCA from a different email address perchance? The approvals team can't seem to find your submission I'm afraid.

**Comment by prydie** [comment]
Thanks for your contribution @Simon-Li!

**Pull request merged**
