### PR TITLE
Update documentation to use mysql.oracle.com/v1 instead of mysql.oracle.com/v1alpha1

### PR DESCRIPTION
**Pull request by cpanato**
Signed-off-by: cpanato <ctadeu@gmail.com>

Following the tutorial, saw the current step is wrong. Update that.

I'm testing that and looks very cool! thanks!

### CODE REVIEW

**Comment by devdattakulkarni** [comment]
@cpanato There are few other places. Example:
https://github.com/oracle/mysql-operator/blob/master/docs/user/clusters.md

**Comment by cpanato** [comment]
Thanks @devdattakulkarni will update

**Comment by cpanato** [comment]
@owainlewis I'm doing the CLA now

**Comment by prydie** [comment]
Hi @cpanato,

This is an artefact of our downgrading the API version for the 0.2 release which we'll be making in the coming days. Merging the documentation updates prior to the release was an oversight, however, at this point, we'd need to revert this commit in a couple of days. Apologies for the confusion!

@owainlewis Do you think it's worth merging this change and reverting at this point (CLA status permitting)?

**Comment by cpanato** [comment]
@prydie thanks!
I submit the CLA, waiting for the result

**Comment by cpanato** [comment]
@prydie the CLA is done :)

**Comment by prydie** [comment]
@cpanato Great, thanks. @owainlewis can you follow up internally, please.

Have you run the unit tests on this branch by any chance? I believe they will fail as we validate the examples against the type definitions to ensure the examples don't get out of date and the types have been updated for the 0.2 release. It might just be simpler to live with the confusion for the next couple of days until the 0.2 release is out perhaps?

**Comment by prydie** [comment]
Apologies for the confusion. This should be resolved now with the release of v0.2.0.

**Comment by cpanato** [comment]
ok

**Comment by prydie** [comment]
Thanks again for your contribution. Hopefully it helped people despite not ending up getting merged.

**Comment by cpanato** [comment]
I'm looking forward to see where I can contribute more for this project

**Pull request closed without merging**
