### PR TITLE
Update tutorial.md

### PR DESCRIPTION
**Pull request by m4oc**
the parameter "-d" is lowercase

### CODE REVIEW

**Comment by owainlewis** [comment]
Thanks @m4oc. Would you mind signing the Oracle Contributor Agreement (CLA) and signing-off your commit so we can merge (see: CONTRIBUTING.md for details)?

The CLA can be found here https://www.oracle.com/technetwork/community/oca-486395.html

If you're comfortable doing that, let us know when it's submitted and we can merge your changes. If that's too much trouble I'd be happy to push a commit incorporating your changes. Obviously we'd love to get you as a contributor.

Let us know if you have any questions.

**Comment by owainlewis** [comment]
I believe there is a difference between OSX and Linux here. OSX using an uppercase flag and lowercase for Ubuntu etc.

**Comment by bweston92** [comment]
@owainlewis that is the case yes. However they both support `--decode`.

So it should be:
```
$ kubectl -n my-namespace get secret my-app-db-root-password -o jsonpath="{.data.password}" | base64 --decode
```

**Comment by owainlewis** [comment]
Opened #187 for cross OS compatibility fix.

**Comment by owainlewis** [comment]
Fixed in #187

**Pull request closed without merging**
